### ISSUE TITLE
OMIT -Wait parameter does not work 

### ISSUE THREAD

**Issue by Gadeberg87** [eapowertools/QlikSenseTask#10]
Hi,

First of all thank you so much for this tool! I use it on all my clients.

I'm facing some problems with the -Wait parameter.
I run the QlikSenseTask using the SQL server agent. And I would like the job in the SQL server agent to finish succesfully right after it have triggered the Sense task, mo matter if the Sense task fails or whatever.

I can see that you should be able to make it return imediately, if you OMIT the -Wait parameter.
But how do you do this exactly? 
Delete it from the config file, just defaults it to 600 seconds. 

Thank you so much for your help.

/Dennis

**Comment by marcusspitzmiller** [comment]
Hi Dennis - Glad you are finding this useful.  So you are saying you want to kick it off and not wait at all, yes?

**Comment by marcusspitzmiller** [comment]
i am thinking you can do a -wait:0 .. Can you try that?  It is either going to work or wait 30 seconds first.
