### ISSUE TITLE
Issue executing bat from from different server 

### ISSUE THREAD

**Issue by gkrish26** [eapowertools/QlikSenseTask#12]
Hi,
Hope you will help me to solve the issue. my requirement is to trigger the sense task when talend job finishes so i have copied the files from my local machine and tried to execute the sense task successfully. but when i tried to call the bat file which is placed in the qliksense server, i am not able to execute. hence i copied the files in the talend server and tried but there is an issue with communication between . so i would like to know the ports which are responsible so that i can open those ports and test.

Thanks in advance,
Gopi

**Comment by gkrish26** [comment]
Error message ( i have changed the server name )
Time, LogLevel, Message
2018_01_05_11_11_15,Information,"Task: CL_TESTING_REFRESH"
2018_01_05_11_11_15,Information,"Proxy: https://XXXX/defproxy"
2018_01_05_11_11_15,Information,"Wait: 600 seconds"
2018_01_05_11_11_15,Information,"Poll: 30 seconds"
2018_01_05_11_11_15,Information,"Log: D:\Hubble_Sripts\Qlik_Sense\CL_TESTING_REFRESH\QlikSenseTask-2.X"
2018_01_05_11_11_15,Information,"Delete Log: -90 days"
2018_01_05_11_11_37,Error,"System.Exception: Couldnt connect to the server at https://XXXX/defproxy , check that the Proxy and QRS are running.  Message: ConnectFailure: Unable to connect to the remote server
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout)
   at QlikSenseTask.Program.Main(String[] args)"
2018_01_05_11_11_37,Information,"Returning Errorlevel 8"

**Comment by marcusspitzmiller** [comment]
Hi, it probably isn't ports.  If you can trigger the task from your local machine, ports are ok.  (Uses 80/443, FYI.).  You should look at the user running the task.  If you are running from your laptop, then you are executing QlikSenseTask with your userid.  So when you move the utility to another machine, make sure the userid it runs under can also have privledges to see and execute the task.  let me know if this helps.

**Comment by yolisvip** [comment]
Hello all

I am on the same situation; I am using Stone Branch to trigger Qlik.
To do so we have an "agent" on the server but is not a "user" per say.
So it doesn't have a windows account associated to the agent.
So when i ran QlikSenseTask the error is the same as Gopi :(
and i am getting that the user doesn't exist and i am not able to add the user to Qlik QMC because it doesn't exist on the windows active directory.
Could you pretty please help me ?

Thank you

**Comment by marcusspitzmiller** [comment]
could you tell me more about the user context then? What is it?  does it run as local_system?  does it have admin privileges on the box?  *something* needs to have rights to the task, obviously.

**Comment by yolisvip** [comment]
the user has administrator right to the server.

when i ran the command whoami i got: rchqlsed3\ubrokerservice
where rchqlsed3 is the name of the server
and ubrokerservice is my userneme 

the error i got is "Unauthorized":
2018_04_04_10_38_42,Error,"System.Exception: Couldnt connect to the server at https://rchqlsed2.na.lennoxintl.com , check that the Proxy and QRS are running.  Message: Unauthorized: 
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2018_04_04_10_38_42,Information,"Returning Errorlevel 8"

However if i do it from my desktop i am able to load the application because i am root admin; since i cant add the user on Qliq QMC because it is not on the active directory i dont know how to do :(

**Comment by marcusspitzmiller** [comment]
If you can do a whoami, that means you are logged into the server with that account?  Or is whoami run through the agent?

If the former, can you login to QMC with that ID?

If the latter, hmm...need to think.

**Comment by yolisvip** [comment]
Thank you so much for relying so fast :)

I am logged through the server using the agent; i can run command lines using python.
I was thinking of changing user once i am inside the server; but that requires a two step process; send the user then the password; so far that is the only solution i can think of.

Excellent work by the way!! thank you

**Comment by marcusspitzmiller** [comment]
Ok. If you are on the server what happens when you go to the QMC when logged in as that account?

**Comment by yolisvip** [comment]
I can't connect to the server because I don't have a password because it is not a windows account :( so I guess my only solution is to find a way to change users using command line

**Comment by marcusspitzmiller** [comment]
qlikSenseTask uses NTLM for authencition.  Sounds like this is not available for this account.  can you look at Qlik-Cli (google it) which has the ability to use certs for authentication?

**Comment by yolisvip** [comment]
Hello Marcus :)

I was able to change the user to an administrator user and now i am getting below error:

2018_04_11_03_08_33,Information,"Task is starting..."
2018_04_11_03_08_33,Error,"System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at QlikSenseJSONObjects.QlikSenseJSONHelper.StartTaskByName(String taskname, Boolean synchronous)
   at QlikSenseTask.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
"
2018_04_11_03_08_33,Information,"Returning Errorlevel 8"

However if i run it from the server it work.

I checked and the Newtonsoft.Json.dll and QlikSenseTask.exe are on the desktop and when i run from the server you can see that the log is fine and my task is getting loaded.
however seems that if i do it from Stone Branch using my Phyton Script it is not recognizing Newtonsoft.Json.dll.

Is there any way to import this file or to work this out ?

I really appreciate your great help

![image](https://user-images.githubusercontent.com/37883101/38640871-1f8d1922-3d9b-11e8-8b6f-22944cf64eb0.png)

**Comment by yolisvip** [comment]
can i just import the dll and using it ?

mport ctypes
#Here you load the dll into python 
MyDllObject = ctypes.cdll.LoadLibrary("C:\\My\\Path\\To\\MyDLL.dll")

**Comment by marcusspitzmiller** [comment]
It is a guess but I am thinking if you are logging in as another user now that user’s working directory is not set to the location of qliksensetask and the dll.  Can you CD into the folder before executing the .exe?

Doubt that loading the dll in python will work but you can try...

**Comment by yolisvip** [comment]
yes i am on that path.
I placed the files on the desktop; and i did a simple test just run "QlikSenseTask" and from the server a log file got created; but if i do the same command from SB i got the response back as:

2018_04_11_06_02_59,Information,"Task: "
2018_04_11_06_02_59,Information,"Proxy: https://uschi-msi4"
2018_04_11_06_02_59,Information,"Wait: 600 seconds"
2018_04_11_06_02_59,Information,"Poll: 30 seconds"
2018_04_11_06_02_59,Information,"Log: C:\Users\jlb\Desktop"
2018_04_11_06_02_59,Information,"Delete Log: -90 days"
2018_04_11_06_02_59,Fatal,"Proxy or Task undefined"

BUT i dont get any file back; 

When i ran the whole command line i got the response back on the application but is not creating any file than and not founding the dll
2018_04_11_03_08_31,Information,"Task: LPP"
2018_04_11_03_08_31,Information,"Proxy: https://rchqlsed2.na.lennoxintl.com"
2018_04_11_03_08_31,Information,"Wait: 600 seconds"
2018_04_11_03_08_31,Information,"Poll: 30 seconds"
2018_04_11_03_08_31,Information,"Log: C:\Users\JLB\Desktop"
2018_04_11_03_08_31,Information,"Delete Log: -90 days"
2018_04_11_03_08_31,Information,"Creating connection..."
2018_04_11_03_08_31,Debug,"Creating web connection..."
2018_04_11_03_08_31,Debug,"Creating CookierAwareWebClient..."
2018_04_11_03_08_31,Debug,"calling /qrs/about"
2018_04_11_03_08_31,Debug,"setting headers"
2018_04_11_03_08_31,Debug,"constructing query string"
2018_04_11_03_08_31,Debug,"calling https://rchqlsed2.na.lennoxintl.com/qrs/about"
2018_04_11_03_08_33,Debug,"{"buildVersion":"16.5.6.0","buildDate":"9/20/2013 10:09:00 AM","databaseProvider":"Devart.Data.PostgreSql","nodeType":1,"sharedPersistence":true,"requiresBootstrap":false,"singleNodeOnly":false,"schemaPath":"About"}"
2018_04_11_03_08_33,Information,"Task is starting..."
2018_04_11_03_08_33,Error,"System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at QlikSenseJSONObjects.QlikSenseJSONHelper.StartTaskByName(String taskname, Boolean synchronous)
   at QlikSenseTask.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
"
2018_04_11_03_08_33,Information,"Returning Errorlevel 8"


thank you

**Comment by Gonccio** [comment]
Hello @marcusspitzmiller 
Thanks for your effort on this great tool and I got the same error (The process exited with non-zero ExitCode (8)), and I saw your comment regarding the ports, I have a cluster environment:
1 Central node
2 Proxy nodes
2 Schedulers
2 engines
My question is do I have to open the ports 80/443 on all the nodes? or just the central node and the schedulers?
Thanks in advance

**Comment by marcusspitzmiller** [comment]
@Gonccio you only need to connect to a proxy that load balances to the central node.  you don't need ports open for all servers.

**Comment by gkrish26** [comment]
Hi,

Check the ports on your machine which you are executing this script whether open or not. if not please open it for the target machine (qlik sense environment) or with in your organization range.

posts should be open inbound : 80,443,4243 and outbound 4242,4747. i am not sure exact port that will establish a connection to your proxy node to execute the task. but if you enable these ports your problem will be resolved.
