### ISSUE TITLE
Message: Forbidden: Your account is inactive. Contact your administrator to activate it.

### ISSUE THREAD

**Issue by yolisvip** [eapowertools/QlikSenseTask#17]
Hello all

I hope you could help me on this issue :(
I have been trying to make it work for days and it is just not happening :(

I download the 3.X.zip on the server; then i extract the folder on the Desktop and then i go where the executable is and simply run this command line:

QlickSenseTask.exe -task:"LPP" -proxy:https://rchqlsed2.na.lennoxintl.com -wait:600

also i tried to go the the link https://rchqlsed2.na.lennoxintl.com/qrs/about on the server 

The website declined to show this webpage - HTP 403

2018_03_28_01_52_19,Information,"Task: LPP"
2018_03_28_01_52_19,Information,"Proxy: https://rchqlsed2.na.lennoxintl.com"
2018_03_28_01_52_19,Information,"Wait: 60 seconds"
2018_03_28_01_52_19,Information,"Poll: 30 seconds"
2018_03_28_01_52_19,Information,"Log: C:\Users\jlb\Desktop\QlikSenseTask-3.X\QlikSenseTask-3.X"
2018_03_28_01_52_19,Information,"Delete Log: -90 days"
2018_03_28_01_52_19,Information,"Creating connection..."
2018_03_28_01_52_19,Debug,"Creating web connection..."
2018_03_28_01_52_19,Debug,"Creating CookierAwareWebClient..."
2018_03_28_01_52_19,Debug,"calling /qrs/about"
2018_03_28_01_52_19,Debug,"setting headers"
2018_03_28_01_52_19,Debug,"constructing query string"
2018_03_28_01_52_19,Debug,"calling https://rchqlsed2.na.lennoxintl.com/qrs/about"
2018_03_28_01_52_20,Debug,"error: The remote server returned an error: (403) Forbidden."
2018_03_28_01_52_20,Error,"System.Exception: Couldnt connect to the server at https://rchqlsed2.na.lennoxintl.com , check that the Proxy and QRS are running.  Message: Forbidden: Your account is inactive. Contact your administrator to activate it.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2018_03_28_01_52_20,Information,"Returning Errorlevel 8"

![image](https://user-images.githubusercontent.com/37883101/38054946-02ef2d9e-329e-11e8-8450-1c6760878811.png)

**Comment by yolisvip** [comment]
I really hope you can help me :)
have a great day

**Comment by yolisvip** [comment]
OMG IT JUST WORKED!!!
I ran it from MY laptop instead from the server!!

IM SO HAPPY!!

great job !!

Thank you so much

**Comment by marcusspitzmiller** [comment]
Great.  Just remember that it will use the credentials of the user you are logged in as, and those credentials need to be able to authenticate, see and run the task.  easy way to check is by logging into the QMC with that user.
