### ISSUE TITLE
Task Runner was failing with error's

### ISSUE THREAD

**Issue by ravinderrr** [eapowertools/QlikSenseTask#18]
Hi,

I was been trying to implement the task runner from Qlikview to Qliksense and also i was trying to run externally to run the tasks externally but i am getting the error as below.

Time, LogLevel, Message
2018_03_29_11_52_51,Information,"Task: Reload task of License monitor"
2018_03_29_11_52_51,Information,"Proxy: http://XXXXX"
2018_03_29_11_52_51,Information,"Wait: 1400 seconds"
2018_03_29_11_52_51,Information,"Poll: 30 seconds"
2018_03_29_11_52_51,Information,"Log: C:\Users\XXXX\Desktop\QlikSenseTask-3.X"
2018_03_29_11_52_51,Information,"Delete Log: -90 days"
2018_03_29_11_52_51,Information,"Creating connection..."
2018_03_29_11_52_51,Debug,"Creating web connection..."
2018_03_29_11_52_51,Debug,"Creating CookierAwareWebClient..."
2018_03_29_11_52_52,Debug,"calling /qrs/about"
2018_03_29_11_52_52,Debug,"setting headers"
2018_03_29_11_52_52,Debug,"constructing query string"
2018_03_29_11_52_52,Debug,"calling http://XXXXXXXXXXX/qrs/about"
2018_03_29_11_52_53,Debug,"error: Unable to connect to the remote server"
2018_03_29_11_52_53,Error,"System.Exception: Couldnt connect to the server at http://g4w9959.houston.hpecorp.net , check that the Proxy and QRS are running.  Message: ConnectFailure: Unable to connect to the remote server
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2018_03_29_11_52_53,Information,"Returning Errorlevel 8"

Even i checked the Proxy and QRS services running perfectly but even though it throws me a same error as above, i have tried changing the HTTP to HTTPS as well, it does't seems to work.

This is an awesome tool, it was working while ago in Qliksense 3.2.3 but after upgrade Qliksense Novemer 2017 Relaease it was not working. Did anybody experienced same scenario please let me know how could i make it work or Any latest version are we going to get.

Thanks,
Ravinder

**Comment by marcusspitzmiller** [comment]
Hi Ravinder - i'm assuming this is the same as we were talking about on linkedin.

1 - if you are using proxy:http://xxxx, then can you actually connect to the QMC using http://xxxx/qmc using the same user running QlikSenseTask?  Note the http, not https.

2- if so, can that user see the task and execute a reload from QMC?

3 - when using https, make sure there are no certificate warnings in chrome.

FYI, am testing on April 2018 at this point, but have certainly had things working on > 3.2.3.

**Comment by ravinderrr** [comment]
Hi Marcus,

Thanks for your Quick Response. 
1) We wanted to implement the external task to run using Qlikview to Qliksense.
2) Here we have Qlikview application run's on schedule time and the we wanted after successfull completion of Qlikview Application then Qliksense has to trigger inorder to avoid time lag between dashboard refresh.
3) We can use QMC but we don't want something individual schedules we wanted some thing once Qlikview completed then Qliksense has trigger using Task runner but it was failing with that error.

**Comment by marcusspitzmiller** [comment]
Hi, I understand what you want to do.  I am asking you do debug using the steps above.  Can you please try the above and let me know the result?

**Comment by ravinderrr** [comment]
Step- 1 Implemented got same error
Time, LogLevel, Message
2018_04_02_10_59_58,Information,"Task: Reload task of XXXX"
2018_04_02_10_59_58,Information,"Proxy: http://XXX.XX.Net/qmc"
2018_04_02_10_59_58,Information,"Wait: 600 seconds"
2018_04_02_10_59_58,Information,"Poll: 30 seconds"
2018_04_02_10_59_58,Information,"Log: C:\Users\XXX\Desktop\QlikSenseTask-3.X"
2018_04_02_10_59_58,Information,"Delete Log: -90 days"
2018_04_02_10_59_59,Information,"Creating connection..."
2018_04_02_10_59_59,Debug,"Creating web connection..."
2018_04_02_10_59_59,Debug,"Creating CookierAwareWebClient..."
2018_04_02_10_59_59,Debug,"calling /qrs/about"
2018_04_02_10_59_59,Debug,"setting headers"
2018_04_02_10_59_59,Debug,"constructing query string"
2018_04_02_10_59_59,Debug,"calling http://XXX.XXX.net/qmc/qrs/about"
2018_04_02_11_00_00,Debug,"error: Unable to connect to the remote server"
2018_04_02_11_00_00,Error,"System.Exception: Couldnt connect to the server at http://XXX.XXX.net/qmc , check that the Proxy and QRS are running.  Message: ConnectFailure: Unable to connect to the remote server
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger)
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger)
   at QlikSenseTask.Program.Main(String[] args)"
2018_04_02_11_00_00,Information,"Returning Errorlevel 8"

Step-2
There are no certificate warnings in chrome but still the same issue

**Comment by marcusspitzmiller** [comment]
http://XXX.XXX.net/qmc/qrs/about is not a valid URL.  I am not asking you to add /qmc to the path.  What I am asking you do to is literally log into the QMC with the same account that runs QlikSenseTask and tell me if you can login or not.

**Comment by ravinderrr** [comment]
Yes,  i can login into QMC.

**Comment by ravinderrr** [comment]
It got worked after checking the Allow HTTP check box in QMC-> Proxies
