### ISSUE TITLE
application quits Unhandled Exception

### ISSUE THREAD

**Issue by jcarpenter9** [eapowertools/QlikSenseTask#20]
Hi. I've tried running version 3.x from the command line and from a QlikView script. Each time the application quits and returns the following in the command window. Can you suggest how I might resolve this?

> Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
> ds of the array.
>    at QlikSenseTask.Program.Main(String[] args)

**Comment by marcusspitzmiller** [comment]
hi, pls provide the qlikview script and command line you are using.  in general, this has not been designed to call like this, but i can look anyway.
