### ISSUE TITLE
Issue using Global Settings config.txt

### ISSUE THREAD

**Issue by artislasmanis** [eapowertools/QlikSenseTask#21]
Hi! Using Global Settings file in a form -proxy:https://localhost -wait:600 it fails with wrong proxy server (see log file):
Time, LogLevel, Message
2018_07_27_10_50_00,Information,"Task: Automatic reload of My Task"
2018_07_27_10_50_00,Information,"Proxy: "https://localhost" -wait:600"
2018_07_27_10_50_00,Information,"Wait: 600 seconds"
When I use it in a form:
-proxy:https://localhost
-wait:600
(space symbol is replaced by CR/LF) then it works ok.

**Comment by marcusspitzmiller** [comment]
Hi yes, this is by design.  You need carriage returns in config.txt
