### ISSUE TITLE
Browser does not support Javascript

### ISSUE THREAD

**Issue by BreizhPancake** [eapowertools/QlikSenseTask#22]
Hello,

When I launch this executable, I get the following error :
"Since your browser does not support JavaScript, you must press the Resume button once to proceed."

I allowed "Scripting" in IE (version11), in internet options.

it's working on another server but not this one.

Do you have any idea ?

Thanks and Regards,

Julie

**Comment by marcusspitzmiller** [comment]
Hi Julie, that is strange.  Can you please provide a screenshot?

**Comment by BreizhPancake** [comment]
Hi,

Thanks for your prompt anwer !
Let's see below screenshot :

![qliksensetaskissue](https://user-images.githubusercontent.com/43448255/45868456-03b10400-bd86-11e8-8a59-94db69b40d0b.png)

**Comment by marcusspitzmiller** [comment]
Ah.  This tool does not support SAML. Only NTLM.  Try pointing to the central virtual proxy where you probably have AD authentication configured.

**Comment by BreizhPancake** [comment]
It's already pointing on central virtual proxy (authentification methos : Ticket)  and nevertheless it's not working ...

**Comment by marcusspitzmiller** [comment]
Ok.  Please provide the command line you are executing and the resulting log file.  i can't see the command you are using from the screenshot.

**Comment by BreizhPancake** [comment]
The command line I use is : 
D:\QlikSenseTask\QlikSenseTask -task:"Refresh Task - Pricing Efficiency" -wait:600 -proxy:https://Serverlink.com/auth

Moreover, you can find attached the corresponding log and  4 screenshots of QMC proxies setup.
I think there is maybe an inconsistency between both virtual proxies (SAML and Central).

Thank you very much for your help.

[Refresh Task - Pricing Efficiency_2018_09_24_10_36_37.log](https://github.com/eapowertools/QlikSenseTask/files/2410305/Refresh.Task.-.Pricing.Efficiency_2018_09_24_10_36_37.log)
![screenshot1_centralproxy](https://user-images.githubusercontent.com/43448255/45945558-64864980-bfdd-11e8-9897-3fdf2b849ba5.JPG)
![screenshot2_centralproxy](https://user-images.githubusercontent.com/43448255/45945559-651ee000-bfdd-11e8-8768-6e0e8041794a.JPG)
![screenshot3_samlproxy](https://user-images.githubusercontent.com/43448255/45945560-651ee000-bfdd-11e8-95f2-f1d2b5c48010.JPG)
![screenshot4_samlproxy](https://user-images.githubusercontent.com/43448255/45945561-651ee000-bfdd-11e8-84bf-ef1398ccddf9.JPG)
