### ISSUE TITLE
Logging changes

### ISSUE THREAD

**Issue by mrackers** [eapowertools/QlikSenseTask#3]
1. I second the request to specify where the log files should be saved. Currently they go to the users current directory.

2. I would like to request a parameter to automatically clean up log entries after a period of time. When the program runs it should look for log files over a certain date and remove them. We are running a lot of jobs a day and our folder already has hundreds of entries.

3. We had a problem when two tasks started at exact same second. It caused the program to crash because the log file was open. Can you append the task name to the beginning of the log file. It would be helpful for finding logs for a particular task.

**Comment by marcusspitzmiller** [comment]
Thanks for the request.  I'll look at this.

About #2 - do you feel it would be better to delete or archive the logs?

**Comment by mrackers** [comment]
I thought about customizing your app and what I would have done is add a number parameter to delete the log files after # of days. I don't see the point in archiving, even the archive would have to be cleaned up eventually. We generated hundreds of entries in just a month.

**Comment by mrackers** [comment]
I used your source code for 2.x and customized it for the logging. The attached zip file is the source code I changed. I added the following parameters/features:

- log: <specify the path where you want to keep the logs>.
I also changed the code so all log files will go to the directory where the exe is at by default regardless where you launch it from.

- deletelog: <delete logs older than # days old>

I changed the log file name so the task name used is part of the file name.

Please review the changes and feel free to use them in your next update. I apologize in advance for not using comments; poor judgment on my part. 

[QlikSenseTaskSource-2.X-Customized-Untested.zip](https://github.com/marcusspitzmiller/QlikSenseTask/files/280800/QlikSenseTaskSource-2.X-Customized-Untested.zip)
I have only tested this lightly so I advise others to be cautious.

**Comment by mrackers** [comment]
I used your source code for 2.x and customized it for the logging. The attached zip file is the source code I changed. I added the following parameters/features:

•log:  I also changed the code so all log files will go to the directory where the exe is at by default regardless where you launch it from.

•deletelog: I changed the log file name so the task name used is part of the file name.

Please review the changes and feel free to use them in your next update. I apologize in advance for not using comments; poor judgment on my part. 

 I have only tested this lightly so I advise others to be cautious.
[QlikSenseTaskSource-2.X-Customized-Untested.zip](https://github.com/marcusspitzmiller/QlikSenseTask/files/280808/QlikSenseTaskSource-2.X-Customized-Untested.zip)

**Comment by marcusspitzmiller** [comment]
Thanks for the code.  I checked it and moved it into master.
