### ISSUE TITLE
TLS1.2

### ISSUE THREAD

**Issue by HermodSv** [eapowertools/QlikSenseTask#32]
Hi.

After the organization went to forced TLS1.2, it looks like QlikSensTask is not managing to trigger a task on Qlik Sense server.
I can see that you have started with tls1.2 on the source code, Any binary soon?

Regards
Hermod

**Comment by marcusspitzmiller** [comment]
Hi, the binaries in master should be supporting tls1.2 now.  https://github.com/marcusspitzmiller/QlikSenseTask/tree/master/QlikSenseTaskSource-3.X/QlikSenseTask/bin/Release

**Comment by marcusspitzmiller** [comment]
note, you will need .net 4.8 on the machine.

**Comment by HermodSv** [comment]
Hi.

Thank you. .NET4.8 is already installed on the servers.

**Comment by rvaheldendaten** [comment]
> Hi, the binaries in master should be supporting tls1.2 now. https://github.com/marcusspitzmiller/QlikSenseTask/tree/master/QlikSenseTaskSource-3.X/QlikSenseTask/bin/Release

@marcusspitzmiller 
Hi Marcus!

Just realized that the direct download under https://github.com/marcusspitzmiller/QlikSenseTask/blob/master/QlikSenseTask-3.X.zip points to an old version (not supporting TLS 1.2). Can you fix this?

Thx,
Roland

**Comment by marcusspitzmiller** [comment]
Hi Roland, check now

From: Roland Vecera ***@***.***>
Reply-To: marcusspitzmiller/QlikSenseTask ***@***.***>
Date: Tuesday, June 7, 2022 at 2:16 AM
To: marcusspitzmiller/QlikSenseTask ***@***.***>
Cc: Marcus Spitzmiller ***@***.***>, Mention ***@***.***>
Subject: Re: [marcusspitzmiller/QlikSenseTask] TLS1.2 (Issue #32)


Hi, the binaries in master should be supporting tls1.2 now. https://github.com/marcusspitzmiller/QlikSenseTask/tree/master/QlikSenseTaskSource-3.X/QlikSenseTask/bin/Release

@marcusspitzmiller<https://github.com/marcusspitzmiller>
Hi Marcus!

Just realized that the direct download under https://github.com/marcusspitzmiller/QlikSenseTask/blob/master/QlikSenseTask-3.X.zip points to an old version (not supporting TLS 1.2). Can you fix this?

Thx,
Roland

**Comment by rvaheldendaten** [comment]
thx!
