### ISSUE TITLE
WHATS IS GOING ON ?

### ISSUE THREAD

**Issue by eldteixeira** [eapowertools/QlikSenseTask#33]
Hello, I have this error occurring every time I try to start a ![Screenshot_1](https://user-images.githubusercontent.com/111124577/184346515-d5f492e3-4a36-4878-8b63-e986a22f0882.png), what could be wrong?
![Screenshot_1_1](https://user-images.githubusercontent.com/111124577/184346681-239ea683-432c-4e57-8c3b-0c396526d032.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/111124577/184346702-284dd658-9bbc-4387-aa2c-02d4cf4a6e45.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/111124577/184346723-b9cdce76-ac14-4aa6-adbb-befdb5953140.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/111124577/184346744-b4e98503-52d2-435d-b935-1af1fbca871c.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/111124577/184346769-3050acc8-cc77-42ac-812e-5af7564a98ef.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/111124577/184346790-2c44fb8a-1eb9-41bd-bc09-0a56df687b40.jpg)

**Comment by eldteixeira** [comment]
Please help me.

**Comment by marcusspitzmiller** [comment]
Hi, it is because you are hitting a proxy using forms auth.  you need to hit a proxy using NTLM /windows auth.

**Comment by eldteixeira** [comment]
Tks a lot. i will try it.
