### ISSUE TITLE
Define Slave QSS that runs the task

### ISSUE THREAD

**Issue by rvaheldendaten** [eapowertools/QlikSenseTask#5]
Hi!

I want to start the task on a specific SLAVE node.
Unfortunately I don't find anything in the API documenation.

Is there any chance to tell Qlik Sense on which QSS-node  the task is started?

Thx,
Roland

**Comment by marcusspitzmiller** [comment]
Hi Roland - this is something you control with sync rules, and you won't find anything in the API for it.  Basically, if the app is available on a node as defined by sync rules, it will be a candidate to reload there.  You can change the sync rules to be more creative than the default.  I like to use custom properties on the apps or streams and say something like App.ReloadNode = Node.ReloadNode with values Node1, Node2, for example.

Does this help?

**Comment by rvaheldendaten** [comment]
Hi Marcus!

thx for the fast response!

I want to sync the app to Node1 and Node2 to provide highavailabilty for the endusers. 
But I want to reload the application by default on Node2 (because less resources are used there). 

So it would be great if I can provide a parameter to QlikSenseTask that hands over the QSS-node. Otherwise I have to hope that Qlik Sense Load balancing picks the correct server.

Roland
