### ISSUE TITLE
Triggered reload task

### ISSUE THREAD

**Issue by epetra** [eapowertools/QlikSenseTask#8]
Hi, is it possible to work with triggered reload tasks? For example I have two tasks and second task starts only after first one. My question would be: How to get information from second reload task (Is it successful or it failed) entering only first task name as variable to -task: parameter? Is it possible?

**Comment by marcusspitzmiller** [comment]
Hi, it is not possible with this tool.  This tool would be called by some enterprise scheduler that can do just what you are describing.  But it is not functionality intended for QlikSenseTask itself.
