### ISSUE TITLE
Bad request: cannot find task

### ISSUE THREAD

**Issue by woutertrappers** [eapowertools/QlikSenseTask#9]
Great tool, thanks for building this!

I keep getting this error message: Bad request: Cannot find a task with the following name, althoug the task does exist. Any ideas how to tackle this issue please?

![image](https://cloud.githubusercontent.com/assets/6561993/20385495/f3e4c060-acb7-11e6-8342-bd326ff666f4.png)

**Comment by marcusspitzmiller** [comment]
Can you show me the command line you are using?

Ex:
qliksensetask -task:"Reload License Monitor" -proxy:https://localhost -wait:600

**Comment by dauledk** [comment]
I know this is an old issue - but I got this message when running the job as a user without the content-admin role in Qlik Sense

**Comment by marcusspitzmiller** [comment]
Ah, ok, thanks.

**Comment by umjohndacosta** [comment]
consider if the user account you are using has access to run tasks / update applications.
